core/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.login, name='login'),
    path('random_match/', views.random_match, name='random_match'),
    path('webp/', views.webp, name='webp')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models

# Kullanıcı tablosu. Login sayfasında kullanıcıyı authenticate edebilmek için oluşturuldu.
class User(models.Model):
    username = models.CharField(max_length=200)
    password = models.CharField(max_length=200)

class SampleApps(models.Model):
    name = models.CharField(max_length=200, blank=True, null=True)
    icon = models.CharField(max_length=200, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    updated_at = models.DateTimeField(auto_now=True, blank=True, null=True)

class SampleScreenshots(models.Model):
    app = models.ForeignKey(SampleApps, related_name='Screenshots', on_delete=models.CASCADE)
    file_name = models.CharField(max_length=200, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    updated_at = models.DateTimeField(auto_now=True, blank=True, null=True)

# Media dosyaları için oluşturulan model
class Document(models.Model):
    description = models.CharField(max_length=200, blank=True)
    document = models.FileField(upload_to='images/')
    uploaded_at = models.DateTimeField(auto_now_add=True)

core/forms.py
from django import forms
from core.models import Document

class DocumentForm(forms.ModelForm):
    class Meta:
        model = Document
        fields = ('description', 'document', )

core/views.py
from django.shortcuts import render, redirect
from core.models import User, SampleApps, Document
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse
from core.forms import DocumentForm
from PIL import Image
import os

def login(request):

    # Sayfa request edildiğinde login penceresi gelsin 
    if request.method == 'GET':
        return render(request, 'login.html')

    # Login html üzerinde POST işlemi yapılırsa htmlde form üzerinden gönderilen
    # parametreler üzerinden işlem yapılsın ve kullanıcı authenticate edilsin.
    # kullanıcı authenticate olursa random_match sayfasına erişebilsin.
    # if request.method == 'POST'
    else:
        # Login parametreleri formdan çekilir 
        username = request.POST.get('username')
        password = request.POST.get('password')
        try:

            # Kullanıcı tablosunda bu parametrelerle kayıtlı olan bir kullanıcı olup olmadığı
            # kontrol edilir. Eğer var ise sisteme giriş yapılır ve session'da bu parametreler
            # tutulur. Yok ise de kullanıcı yeniden login sayfasına yönlendirilir ve tekrar 
            # doğru parametreleri girene kadar giriş yapması gerekir.
            User.objects.get(username=username, password=password)
            print('Authenticated')
            request.session['is_authenticated'] = True
            return redirect('/random_match/')
        except:
            print('Not Authenticated')
        return redirect('/')

@csrf_exempt
def random_match(request):
    if request.method == 'GET':
        if request.session.get('is_authenticated'):
            """ Sayfa ilk yüklendiğinde htmldeki dropdowna uygulamalar yüklenmelidir.
            Bu yüzden get metodu çağrıldığında veritabanından uygulamaları çekiyoruz
            ve context içerisinde htmlye gönderiyoruz."""
            context = {
                'apps':SampleApps.objects.all(),
            }
            return render(request, 'random_match.html', context)
        else:
            return redirect('/')

    # Eğer sayfa üzerinde post requesti atılmış ise burası çalışır
    else:

        # Eğer sistemde mevcut olan bir uygulama adı girilmişse buradan uygulama 
        # sorgulanıp döndürülür. Mevcut olmayan bir uygulma girilmiş ise de herhangi
        # bir işlem yapılmaz. Ayrıca bir uygulama seçilmiş ise bu aksiyon uygulama seçme aksiyonudur.
        # Yani 1. bloğa yerleştirme aksiyonudur. Bu yüzden aksiyon parametresi de kontrol edilmektedir.
        if request.POST.get('app_id') and request.POST.get('action') == 'select_app':
            app_id = request.POST.get('app_id')

            # Seçilen uygulamayı post edilen id ile veritabanı üzerinden
            # sorgulatıyoruz ve bu uygulmaya ait gerekli screenshotların hepsini
            # veritabanından sorgulatıp response olarak döndürüyoruz.
            app = SampleApps.objects.get(id=app_id)
            ss = app.Screenshots.all()

            # Uygulamaya ait screenshotları veritabanında sorgulatıp liste olarak elde ettik
            # liste içerisinde tuplelar var ise ve biz böyle bir yapı ile tupleı toplar isek
            # flatten edilmiş bir tuple elde ederiz ve bu tupleı listeye dönüştürerek istediğimiz
            # screenshotları tek bir liste içerisinde elde edebiliriz.
            ss_list = list(sum(ss.values_list('file_name'),()))

            # Responseu ajaxa döndürüyoruz ve ayrıca screenshotların yanında oyunun ana görselini de
            # response olarak döndürüyoruz.
            return JsonResponse({'ss_list':ss_list,
                                'icon':app.icon})

        # Aksiyon randomize ise ikinci bloğa yerleştirme işlemidir. Bu yüzden bu blok çalışır.
        elif request.POST.get('action') == 'randomize':

            # Burada da birinci bloğa yerleştirmek için yapılan işlemlerin benzerleri yapılacak.
            # Tek fark id'nin random olarak üretilmesi ve bir önceki id'nin mevcut id'ye eşit olmaması

            # Veritabanından uygulamaları rastgele sıralarız ve ilk kaydı döndürürüz. Böylece 
            # rastgele bir oyun elde etmiş oluruz. 
            # NOT!!: Bu metod çok performanslı değildir ancak veritabanında şuan çok az sayıda
            # kayıt bulunduğundan kullanılmasında sakınca görülmemiştir.

            # Ayrıca random olarak veritabanından çekilen oyun bir önceki oyuna eşit olmayıncaya
            # kadar yeniden üretilir ki bir önceki oyundan farklı bir oyun elde edilsin. 
            app = SampleApps.objects.order_by("?").first()
            while app.id == request.session.get('is_same'):
                app = SampleApps.objects.order_by("?").first()
            
            # while fonksiyonundan çıkıldığında is_same parametresi mevcut uygulama ile güncellenir
            # böylece bir sonraki uygulama üretilirken bir sonraki uygulama da bu uygulama ile
            # karşılaştırılır. Ve bu işlem bu şekilde devam eder ve böylece aynı oyunu hiçbir zaman
            # elde etmemiş oluruz. Güncellemeyi sessiona kaydederek yapıyoruz.
            request.session['is_same'] = app.id

            # Geri kalan işlemler bir önceki aksiyonda uygulanan işlemler ile aynı olacaktır.
            ss = app.Screenshots.all()   
            ss_list = list(sum(ss.values_list('file_name'),())) 

            return JsonResponse({'ss_list':ss_list,
                    'icon':app.icon})

# Görselin yükleneceği sayfa
def webp(request):
    if request.method == 'POST':
        form = DocumentForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()

            # imaj verileri veritabanına yüklendikten ve imaj mediaya yüklendikten sonra
            # yüklenen imajın pathini veritabanından çekiyoruz ve elde ettiğimiz path ile de
            # imajı mediadan çekerek üzerinde webpye dönüştürme işlemi yapıyoruz.
            filepath = Document.objects.last().document

            # görsel jpg veya png ise işlem yapılsın. Filepath bir filefield objesi olduğu için
            # uzantı kontrolünü yapabilmek için stringe dönüştürüyoruz.
            if str(filepath).split('.')[1] in ['jpg', 'png']:
                im = Image.open(filepath).convert("RGB")

                # media klasöründe webp sonucunun oluşturulacağı klasör açılmış olup
                # bu klasör içerisine webp dosyası kaydedilmiştir. Htmlde
                # bu klasör üzerinden görsele ulaşacağız. (/media/webp_result/output.webp)
                im.save('media/webp_result/output.webp', "webp")

                # sessionda boolean value tutuldu. Bunun nedeni ilk post ettiğimizde get üzerinde
                # renderın output imaj ile yapılması gerektiğinden. Çünkü post ettiğimizde 
                # yani upload ettiğimizde imajı sayfada görmeliyiz. 
                request.session['webp_result'] = True
            return redirect('/webp/')
    else:

        # Authenticate kontrolünü yine yapıyoruz get yaparken
        if request.session.get('is_authenticated'):
            form = DocumentForm()

            # post üzerinden get edilmişse bu imajın upload edildiği anlamına gelmektedir. Böylece
            # imajı basarız ve ardından boolean değişkeni false yaparız ki normal bir get işlemi yapıldığında
            # yani sayfa normal bir şekilde yüklendiğinde imaj gelmesin. İmaj upload edildiğinde basılmalı.
            if request.session.get('webp_result') == True:
                request.session['webp_result'] = False

                # isWebpResult parametresi htmldeki kontrol için oluşturuldu. Eğer posttan get
                # yapmışsak imaj gösterilmelidir. Ancak normal get yapmışsak htmlye gönderdiğimiz
                # boolean değişkeni false olmalıdır ve img tagı basılmamalıdır.
                return render(request, 'webp.html', {'form':form, 'isWebpResult':True})
            else:
                return render(request, 'webp.html', {'form':form, 'isWebpResult':False})
        return redirect('/')

core/templates/login.html
{% load static %}

<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}"/>
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!------ Include the above in your HEAD tag ---------->

<div class="wrapper fadeInDown">
  <div id="formContent">

    <!-- Login Form -->
    <form action="" method="POST">
      {% csrf_token %}
      <input type="text" id="login" class="fadeIn second" name="username" placeholder="login">
      <input type="text" id="password" class="fadeIn third" name="password" placeholder="password">
      <input type="submit" class="fadeIn fourth" value="Log In">
    </form>

  </div>
</div>

core/templates/random_match.html
<!doctype html>

{% load static %}

<html lang="en">
  <head>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>Random Match</title>
  </head>
  <body>
    <div class="container btn-group" style="margin-top:25px;">
        <input id="select-app" class="form-control" autocomplete="off" list="datalistOptions" id="exampleDataList" placeholder="Select App" style="width:200px; margin-left:500px;">
        <datalist id="datalistOptions">
          {% for app in apps %}
            <option data-value={{ app.id }} value="{{ app.name }}">
          {% endfor %}
        </datalist>
        <button id="randomize" type="button" style="margin-left:25px;">Randomize</button>
        <p style="margin-left: 100px;"><a href="{% url 'webp' %}">Webp Dönüştürücü Sayfasına Git</a></p>
    </div>
    <div class="container" style="margin-top:50px;">
        <div class="row">
            <div id="carousel-1" class="col-md-4 mx-auto" style="border:5px; border-style:solid; padding:0px; height:425px;">
                      <!-- Buradaki veri dinamik olarak javascriptten geliyor -->       
            </div>
            <div id="carousel-2" class="col-md-4 mx-auto" style="border:5px; border-style:solid; padding:0px;">
                      <!-- Buradaki veri dinamik olarak javascriptten geliyor -->    
            </div>
        </div>
    </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    
    <!-- <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script> -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="{% static 'js/random_match.js' %}"></script>
  </body>
</html>

core/templates/webp.html
{% load static %}

<style>
  form {
      text-align : center;
  }
  .button {
      display: block;
      height: 100px;
      width: 300px;
      text-align: center;
      margin: 0 auto;
  }
  #id_description {
    margin: 0 auto;
  }
  #id_document {
    width:20%;
  }
  </style>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
<!------ Include the above in your HEAD tag ---------->


<div class="container">
  <form method="post" action="" enctype="multipart/form-data" style="margin-top:20px;">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Upload</button>
  </form>

  <p style="text-align:center;"><a href="{% url 'random_match' %}">Random Match Sayfasına Git</a></p>
</div>
<div>
  <!-- webp görselinin basılacağı kısım -->
  <!-- Png upload edildikten sonra eğer webp resultu dönmüş ise dive webp görseli basılır. -->
  {% if isWebpResult %}
    <img src="../media/webp_result/output.webp/" style="margin-left:300px; width:640px; height:400px;">
  {% endif %}
</div>

<script>
  document.ready(function(){

  })
</script>